### ISSUE TITLE
Imports happen relative to state dir rather than pillar?

### ISSUE THREAD

**Issue by raddessi** [jgraichen/salt-tower#11]
Hi, first off I want to say thank you for this project! It adds functionality to salt that is sorely needed. I'm starting to migrate my projects over right now.

**Describe the bug**
I have a few states that import gpg file contents from files outside the pillars just to keep the pillars clean using syntax like `{%- import_yaml './bar.sls' as bar_pillar %}`, but it seems that when using tower salt ends up looking for the files under the state directory rather than the pillar directory. Is this intended?

**To Reproduce**
Create a pillar `foo.sls` with:
```
{%- import_yaml './bar.sls' as bar_pillar %}
foo: {{ bar_pillar.bar }}
```
And the corresponding pillar file `bar.sls` in the same directory:
```
bar: baz
```
then add `foo` to the list of included pillars in the tower top file.
The master log should show messages about the file `bar.sls` not being found. If you move that file to the state dir it should be found however.

**Expected behavior**
Standard salt imports in pillars do happen relative to the directory of the pillar file being rendered, it would be ideal if this followed the same behavior.

**Environment information:**
 - Salt version: 3002.5
 - Python version 3.8
 - Operating system Fedora 32

**Additional context**
NA

**Comment by jgraichen** [comment]
Unfortunately this triggers some edge cases with how salt internals work. The salt-tower ext pillar does reuse the renderers from salt, but they do behave differently if they think they are rendering 1) something, 2) states, or 3) pillars. If they think they are currently rendering a state file they will look up files on the salt master (or local cache directory) based on the global `file_roots` option. If they think they currently render a pillar file, they will look up files directly in `pillar_roots`. ([See here](https://github.com/saltstack/salt/blob/2220edc0b2dd21352786d15552367266ee770099/salt/utils/templates.py#L396))

Unfortunately this is not customizable in any way for salt-tower (or any plugin) when invoking salt to compile a template. Therefore, it is currently impossible to have files looked up relative to e.g. the tower base directory. I've pushed a few changes to have salt-tower explicitly workaround the "special" behavior of some renderers. They should look up files relative to *the current template file* now. The behavior might still differ to salts own pillars because they use their own file lookup implementation for JINJA. 

```
# tower.sls
base:
  - dir/init.sls

# dir/init.sls
{% include "data.yaml" %}

# dir/data.yaml
key: 1
```

The above will result in `key: 1`. This might work in your use case if all files are loaded relative only.

I've also added a salt master config option `salt_tower.unstable_enable_saltenv` to change the options passed to renderers. If set to `True`, salt-tower will call the renderers somewhat similar to how salt renders its own pillar files. This might work well if you have your `tower.sls` in the `pillar_roots` directory. It heavily depends on passing some internal flags and might if salt changes their code, therefore it defaults to `False` right now.

You can test this by changing the salt-tower source to this:

```yaml
gitfs_remotes:
  - https://github.com/jgraichen/salt-tower.git:
    - base: 7e0139c
```

**Comment by raddessi** [comment]
Thanks for that link, I went digging for 20min but couldn't track down where some of the logic was handled in the upstream code.

This does make sense, thank you for the details. Unfortunately we don't currently `include` the entire pillar contents each time, we use  `import` to use the relative sls files as a storage system to keep the on-disk layout sane and the main pillars somewhat small. I may just migrate away from that however, I think it should be doable especially with the stacking that tower lets you do.

> This might work well if you have your tower.sls in the pillar_roots directory.
 
I do! Is that actually not expected? I had wondered about that based on the wording of some parts of this (tower) and the other gitstack/pillarstack module instructions.

Thank you so much for the patch set to play with! I'll check that out as soon as possible and report back here.

**Comment by jgraichen** [comment]
> Unfortunately we don't currently `include` the entire pillar contents each time, we use `import` [..]

I used `include` here, which I used for some manual testing due to being less to type, but the actual [test case](https://github.com/jgraichen/salt-tower/blob/7e0139ccacbadaf4cb2af8d70f6346be12822d97/test/pillar/test_tower.py#L527) uses `import_yaml` too. It works the same as `include` regarding looking up the target file in JINJA. Everything that is described above should be applicable to `import_yaml` too.

> I do! Is that actually not expected?

I actually do that too, basically because my whole pillar is tower only, but it isn't strictly necessary. The `ext_pillar` can be configured to use a different directory, for example when working with multiple saltenvs, or using it for some extra data only.

**Comment by raddessi** [comment]
This works absolutely perfectly! I can not say thank you enough :) Did you really get all these changes done in a few hours? There's some great comments in there about the internal workings of the pillar system. I wish there was a really good doc covering the internal flow and logic structures. It's taken me a long time to even understand the small parts that I do so well done on your part. 

If there is anything I can do to test or help out in another way I'll put some time in, from my few days of heavy use this module is exactly what I have been looking for. I'm extremely grateful for the efforts and care of documentation.

**Comment by jgraichen** [comment]
Thanks! I spend more time in salts source code then I would have wished for, but it does help to remember the quirks present and how to work around them.

I will soon start adding standalone documentation on salt-towers modules, how to use it and how I write states and pillars for salt-tower. You are welcome to read, test, correct and improve them too. Especially if you are going "all-in" too, it would be a very valuable new perspective.

As this bug here is solved, I will close the ticket for now. If you have any more issues, or wishes, please open up new tickets, or write an email to the list.
